// This file automatically generated by:
//   Apache Etch 1.3.0-incubating (LOCAL-0) / java 1.3.0-incubating (LOCAL-0)
//   Thu Sep 26 14:54:45 KST 2013
// This file is automatically created and should not be edited!

package com.obigo.weblink;

import org.apache.etch.util.core.Who;
import org.apache.etch.bindings.java.msg.Message;
import org.apache.etch.bindings.java.support.DeliveryService;
import org.apache.etch.bindings.java.support.Pool;
import org.apache.etch.bindings.java.support.StubHelper;
import org.apache.etch.bindings.java.support._Etch_AuthException;
import org.apache.etch.bindings.java.support.Pool.PoolRunnable;

/**
 * Message to call translator for WebLinkClient.
 */
@SuppressWarnings("unused")
public class StubWebLinkClient extends StubWebLink<WebLinkClient>
{
	/**
	 * Stub for WebLinkClient.
	 * @param svc the delivery service.
	 * @param obj the implementation of WebLinkClient responsive to requests.
	 * @param queued thread pool used to run AsyncMode.QUEUED methods.
	 * @param free thread pool used to run AsyncMode.FREE methods.
	 */
	public StubWebLinkClient( DeliveryService svc, WebLinkClient obj, Pool queued, Pool free )
	{
		super( svc, obj, queued, free );
	}
	
	static
	{
	}

	/**
	 * Method used to force static initialization.
	 */
	public static void init()
	{
		// nothing to do.
	}
	
	static
	{
	}
}
