
// This file automatically generated by:
//   Apache Etch 1.3.0-incubating (LOCAL-0) / c 1.3.0-incubating (LOCAL-0)
//   Wed Sep 11 19:40:10 KST 2013
// This file is automatically created and should not be edited!

#include "weblink_server_impl.h"
#include "weblink_valufact.h"
#include "etch_url.h"
#include "etch_arrayval.h"
#include "etch_binary_tdo.h"
#include "etch_exception.h"
#include "etch_general.h"
#include "etch_log.h"
#include "etch_map.h"
#include <stdio.h>

unsigned short CLASSID_WEBLINK_SERVER_IMPL;	
	
	
char* WEBLINK_ETCHSIMP = "SIMP";

/* generated signatures */
int destroy_weblink_server_implx(void*);
weblink_server_impl* init_weblink_server_impl(struct weblink_remote_client*, etch_object_destructor);


/* - - - - - - - -    
 * instantiation
 * - - - - - - - -   
 */

/**
 * new_weblink_server_impl()
 * weblink_server_impl constructor.
 * add your custom initialization and virtual method overrides here.
 */
weblink_server_impl* new_weblink_server_impl(struct weblink_remote_client* client) 
{
    weblink_server_impl* pserver  /* allocate object */
        = init_weblink_server_impl(client, destroy_weblink_server_implx);	
    i_weblink_server* pserver_base = pserver->weblink_server_base;
    ((etch_object*)pserver_base)->class_id = get_dynamic_classid_unique(&CLASSID_WEBLINK_SERVER_IMPL);
    /* add virtual method overrides, if any, here */
    //etchmap_insertxw(pserver_base->virtuals, weblink_valufact_get_static()->str_weblink_xxx, implementation, FALSE);

    return pserver;
}


/**
 * destroy_weblink_server_implx()
 * destructor for any user allocated memory.
 * this code is invoked by the private perf_client_impl destructor,
 * via perf_client.destroyex(). add code here to destroy any memory you  
 * may have allocated for your custom perf_client implementation.
 */
int destroy_weblink_server_implx(void* data)
{
    /*
      weblink_server_impl* thisx = (weblink_server_impl*)data;
     */

    return 0;
}

/* - - - - - - - - - - - - - - - - - - -
 * session interface method overrides
 * - - - - - - - - - - - - - - - - - - -
 */

 /* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 * implementations of weblink_server messages from server, if any 
 * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 */
 
