
// This file automatically generated by:
//   Apache Etch 1.3.0-incubating (LOCAL-0) / c 1.3.0-incubating (LOCAL-0)
//   Wed Sep 11 19:40:10 KST 2013
// This file is automatically created and should not be edited!

/*
 * weblink_client_main.h
 * client exe main() private header
 */

#ifndef WEBLINK_CLIENT_MAIN_H
#define WEBLINK_CLIENT_MAIN_H

#include "etch_runtime.h"
#include "weblink_helper.h"
#include "weblink_client_impl.h"
#include "weblink_remote_server.h"

#ifdef __cplusplus
extern "C" {
#endif

/*
 * weblink_listener_start(pplistener, uri, waitupms)
 * Start the listener at the given uri, waiting waitupms microseconds for listener startup.
 * The created listener is saved at address pointed to by pplistener.
 */
extern etch_status_t weblink_listener_start(i_sessionlistener** pplistener, wchar_t* uri, int waitupms);

/*
 * weblink_listener_stop(plistener, waitupms)
 * Stop the listener given by plistener, waiting waitupms microseconds to stop.
 */
extern etch_status_t weblink_listener_stop(i_sessionlistener* plistener, int waitupms);

#ifdef __cplusplus
} //extern "C"
#endif

#endif /* WEBLINK_CLIENT_MAIN.H */
