
// This file automatically generated by:
//   Apache Etch 1.3.0-incubating (LOCAL-0) / c 1.3.0-incubating (LOCAL-0)
//   Wed Sep 11 19:40:10 KST 2013
// This file is automatically created and should not be edited!

#ifndef WEBLINK_CLIENT_IMPL_H
#define WEBLINK_CLIENT_IMPL_H

#include "weblink_client.h"
#include "etch_transport.h"

#ifdef __cplusplus
extern "C" {
#endif

extern unsigned short CLASSID_WEBLINK_CLIENT_IMPL;

//typedef struct weblink_remote_server weblink_remote_server;

/**
 * weblink_client_impl
 * your custom implementation of weblink_client. add methods here 
 * to provide implementations of messages from the client, if any.
 */
typedef struct weblink_client_impl
{
    etch_object object;  

    i_weblink_client* weblink_client_base; /* owned */
    i_weblink* iweblink; /* not owned */
    struct weblink_remote_server* server; /* not owned */

    int (*destroyex) (void*);  /* user memory destructor */

    /* - - - - - - - - - - - -
     * objsession
     * - - - - - - - - - - - -
     */
    i_objsession* iobjsession;  /* owned by base */
    /* note that iobjsession->thisx is set to this weblink_client_impl* */
    etch_session_control _session_control;
    etch_session_notify  _session_notify;
    etch_session_query   _session_query;

} weblink_client_impl;

/* constructor */
weblink_client_impl* new_weblink_client_impl (struct weblink_remote_server*);

#ifdef __cplusplus
} //extern "C"
#endif

#endif /* WEBLINK_CLIENT_IMPL_H */
