
// This file automatically generated by:
//   Apache Etch 1.3.0-incubating (LOCAL-0) / c 1.3.0-incubating (LOCAL-0)
//   Wed Sep 11 19:40:10 KST 2013
// This file is automatically created and should not be edited!

#ifndef WEBLINK_SERVER_IMPL_H
#define WEBLINK_SERVER_IMPL_H

#include "weblink_server.h"
#include "etch_transport.h"

#ifdef __cplusplus
extern "C" {
#endif

extern unsigned short CLASSID_WEBLINK_SERVER_IMPL;

//typedef struct weblink_remote_client weblink_remote_client;

/**
 * weblink_server_impl
 * your custom implementation of weblink_server. add methods here 
 * to provide implementations of messages from the client, if any.
 */
typedef struct weblink_server_impl
{
    etch_object object;  

    i_weblink_server* weblink_server_base; /* owned */
    i_weblink* iweblink; /* not owned */
    struct weblink_remote_client* client; /* not owned */

    int (*destroyex) (void*);  /* user memory destructor */

    /* - - - - - - - - - - - -
     * objsession
     * - - - - - - - - - - - -
     */
    i_objsession* iobjsession;  /* owned by base */
    /* note that iobjsession->thisx is set to this weblink_server_impl* */
    etch_session_control _session_control;
    etch_session_notify  _session_notify;
    etch_session_query   _session_query;

} weblink_server_impl;

/* constructor */
weblink_server_impl* new_weblink_server_impl (struct weblink_remote_client*);

#ifdef __cplusplus
} //extern "C"
#endif

#endif /* WEBLINK_SERVER_IMPL_H */
