// This file automatically generated by:
//   Apache Etch 1.3.0-incubating (LOCAL-0) / java 1.3.0-incubating (LOCAL-0)
//   Wed Sep 25 20:31:58 KST 2013
// This file is automatically created for your convenience and will not be
// overwritten once it exists! Please edit this file as necessary to implement
// your service logic.

package com.obigo.weblink;

/**
 * Your custom implementation of BaseWebLinkServer. Add methods here to provide
 * implementations of messages from the client.
 */
public class ImplWebLinkServer extends BaseWebLinkServer
{
	/**
	 * Constructs the ImplWebLinkServer.
	 *
	 * @param client a connection to the client session. Use this to send a
	 * message to the client.
	 */
	public ImplWebLinkServer( RemoteWebLinkClient client )
	{
		this.client = client;
	}
	
	/**
	 * A connection to the client session. Use this to send a
	 * message to the client.
	 */
	@SuppressWarnings( "unused" )
	private final RemoteWebLinkClient client;

	// TODO insert methods here to provide implementations of WebLinkServer
	// messages from the client.
}