// This file automatically generated by:
//   Apache Etch 1.3.0-incubating (LOCAL-0) / java 1.3.0-incubating (LOCAL-0)
//   Wed Sep 25 20:31:58 KST 2013
// This file is automatically created and should not be edited!

package com.obigo.weblink;


/**
 * Call to message translator for WebLinkServer.
 */
@SuppressWarnings("unused")
public final class RemoteWebLinkServer extends RemoteWebLink implements WebLinkServer
{
	/**
	 * Constructs the RemoteWebLinkServer.
	 *
	 * @param svc
	 * @param vf
	 */
	public RemoteWebLinkServer( org.apache.etch.bindings.java.support.DeliveryService svc, org.apache.etch.bindings.java.msg.ValueFactory vf )
	{
		super( svc, vf );
	}

	/**
	 * {@link _Async} class instance used to hide asynchronous message
	 * implementation. Use this to invoke the asynchronous message
	 * implementations.
	 */
	public final _Async _async = new _Async();

	/**
	 * {@link _Async} class instance used to hide asynchronous message
	 * implementation. This is here for backwards compatibility only, use
	 * {@link #_async} instead.
	 * @deprecated
	 */
	@Deprecated
	public final _Async _inner = _async;

	public final void remote_control(
		com.obigo.weblink.WebLink.RemoteControl control
	)
	{
		_async._end_remote_control( _async._begin_remote_control(
			control
		) );
	}

	public final com.obigo.weblink.WebLink.RadioStation[] radio_station_list(
	)
	{
		return
		_async._end_radio_station_list( _async._begin_radio_station_list(
		) );
	}

	public final void radio_station_select(
		Integer radio_station_id
	)
	{
		_async._end_radio_station_select( _async._begin_radio_station_select(
			radio_station_id
		) );
	}

	/**
	 * Asynchronous implementation of service methods.
	 */
	public final class _Async extends RemoteWebLink._Async
	{

		/**
		 * Begins a call to remote_control.
		 *
		 * @return mailbox used to retrieve the result using _end_remote_control.
		 * @see RemoteWebLinkServer#remote_control
		 * @see #_end_remote_control
		 */
		public final org.apache.etch.bindings.java.support.Mailbox _begin_remote_control(
			com.obigo.weblink.WebLink.RemoteControl control
		)
		{
			org.apache.etch.bindings.java.msg.Message _msg = _newMessage( ValueFactoryWebLink._mt_com_obigo_weblink_WebLink_remote_control );
			_msg.put( ValueFactoryWebLink._mf_control, control );
			return _begincall( _msg );
		}
		
		/**
		 * Ends a call to remote_control.
		 *
		 * @param mb mailbox returned by _begin_remote_control.
		 *
		 * @see RemoteWebLinkServer#remote_control
		 * @see #_begin_remote_control
		 */
		public final void _end_remote_control( org.apache.etch.bindings.java.support.Mailbox mb )
		{
			try
			{
				_endcall( mb,
					ValueFactoryWebLink._mt_com_obigo_weblink_WebLink__result_remote_control  );
			}
			catch ( Exception e )
			{
				if (e instanceof RuntimeException) throw (RuntimeException) e;
				throw new RuntimeException( "unexpected exception from peer: "+e, e );
			}
		}

		/**
		 * Begins a call to radio_station_list.
		 *
		 * @return mailbox used to retrieve the result using _end_radio_station_list.
		 * @see RemoteWebLinkServer#radio_station_list
		 * @see #_end_radio_station_list
		 */
		public final org.apache.etch.bindings.java.support.Mailbox _begin_radio_station_list(
		)
		{
			org.apache.etch.bindings.java.msg.Message _msg = _newMessage( ValueFactoryWebLink._mt_com_obigo_weblink_WebLink_radio_station_list );
			return _begincall( _msg );
		}
		
		/**
		 * Ends a call to radio_station_list.
		 *
		 * @param mb mailbox returned by _begin_radio_station_list.
		 *
		 * @see RemoteWebLinkServer#radio_station_list
		 * @see #_begin_radio_station_list
		 */
		public final com.obigo.weblink.WebLink.RadioStation[] _end_radio_station_list( org.apache.etch.bindings.java.support.Mailbox mb )
		{
			try
			{
				return
					(com.obigo.weblink.WebLink.RadioStation[])
						_endcall( mb,
							ValueFactoryWebLink._mt_com_obigo_weblink_WebLink__result_radio_station_list );
			}
			catch ( Exception e )
			{
				if (e instanceof RuntimeException) throw (RuntimeException) e;
				throw new RuntimeException( "unexpected exception from peer: "+e, e );
			}
		}

		/**
		 * Begins a call to radio_station_select.
		 *
		 * @return mailbox used to retrieve the result using _end_radio_station_select.
		 * @see RemoteWebLinkServer#radio_station_select
		 * @see #_end_radio_station_select
		 */
		public final org.apache.etch.bindings.java.support.Mailbox _begin_radio_station_select(
			Integer radio_station_id
		)
		{
			org.apache.etch.bindings.java.msg.Message _msg = _newMessage( ValueFactoryWebLink._mt_com_obigo_weblink_WebLink_radio_station_select );
			_msg.put( ValueFactoryWebLink._mf_radio_station_id, radio_station_id );
			return _begincall( _msg );
		}
		
		/**
		 * Ends a call to radio_station_select.
		 *
		 * @param mb mailbox returned by _begin_radio_station_select.
		 *
		 * @see RemoteWebLinkServer#radio_station_select
		 * @see #_begin_radio_station_select
		 */
		public final void _end_radio_station_select( org.apache.etch.bindings.java.support.Mailbox mb )
		{
			try
			{
				_endcall( mb,
					ValueFactoryWebLink._mt_com_obigo_weblink_WebLink__result_radio_station_select  );
			}
			catch ( Exception e )
			{
				if (e instanceof RuntimeException) throw (RuntimeException) e;
				throw new RuntimeException( "unexpected exception from peer: "+e, e );
			}
		}

		// Mixin Methods
	}
}
