// This file automatically generated by:
//   Apache Etch 1.3.0-incubating (LOCAL-0) / java 1.3.0-incubating (LOCAL-0)
//   Wed Sep 25 20:31:58 KST 2013
// This file is automatically created and should not be edited!

package com.obigo.weblink;



@SuppressWarnings("unused")
public interface WebLinkServer extends WebLink
{
	/**
	 */
	public void remote_control(
		com.obigo.weblink.WebLink.RemoteControl control
	)
	;
	/**
	 */
	public com.obigo.weblink.WebLink.RadioStation[] radio_station_list(
	)
	;
	/**
	 */
	public void radio_station_select(
		Integer radio_station_id
	)
	;
}
