// This file automatically generated by:
//   Apache Etch 1.3.0-incubating (LOCAL-0) / java 1.3.0-incubating (LOCAL-0)
//   Wed Sep 25 20:31:58 KST 2013
// This file is automatically created and should not be edited!

package com.obigo.weblink;



@SuppressWarnings("unused")
public interface WebLinkClient extends WebLink
{
	// no CLIENT direction items defined.
}
