// This file automatically generated by:
//   Apache Etch 1.3.0-incubating (LOCAL-0) / java 1.3.0-incubating (LOCAL-0)
//   Thu Sep 26 14:54:45 KST 2013
// This file is automatically created and should not be edited!
// Re-implement these methods by overriding them in ImplWebLinkServer.

package com.obigo.weblink;

import org.apache.etch.bindings.java.support.ObjSession;


/**
 * Base implementation of WebLinkServer, with default method implementations
 * which throw UnsupportedOperationException. Extend this class to provide
 * implementations of messages from the client.
 *
 * @see ImplWebLinkServer
 */
public class BaseWebLinkServer implements WebLinkServer, ObjSession
{
	public Object _sessionQuery( Object query ) throws Exception
	{
		throw new UnsupportedOperationException( "unknown query: "+query );
	}

	public void _sessionControl( Object control, Object value ) throws Exception
	{
		throw new UnsupportedOperationException( "unknown control: "+control );
	}

	public void _sessionNotify( Object event ) throws Exception
	{
		if (event instanceof Throwable)
			((Throwable) event).printStackTrace();
	}

	public void remote_control
	(
		com.obigo.weblink.WebLink.RemoteControl control
	)
	{
		throw new UnsupportedOperationException( "remote_control" );
	}

	public com.obigo.weblink.WebLink.RadioStation[] radio_station_list
	(
	)
	{
		throw new UnsupportedOperationException( "radio_station_list" );
	}

	public Integer radio_station_count
	(
	)
	{
		throw new UnsupportedOperationException( "radio_station_count" );
	}

	public com.obigo.weblink.WebLink.RadioStation radio_station_get_at
	(
		Integer index
	)
	{
		throw new UnsupportedOperationException( "radio_station_get_at" );
	}

	public void radio_station_select
	(
		Integer radio_station_id
	)
	{
		throw new UnsupportedOperationException( "radio_station_select" );
	}
}
