// This file automatically generated by:
//   Apache Etch 1.3.0-incubating (LOCAL-0) / java 1.3.0-incubating (LOCAL-0)
//   Thu Sep 26 14:54:45 KST 2013
// This file is automatically created and should not be edited!

package com.obigo.weblink;

import org.apache.etch.bindings.java.msg.AsyncMode;
import org.apache.etch.bindings.java.msg.Direction;
import org.apache.etch.bindings.java.msg.Field;
import org.apache.etch.bindings.java.msg.ImportExportHelper;
import org.apache.etch.bindings.java.msg.StructValue;
import org.apache.etch.bindings.java.msg.Type;
import org.apache.etch.bindings.java.msg.TypeMap;
import org.apache.etch.bindings.java.msg.ValueFactory;
import org.apache.etch.bindings.java.support.Class2TypeMap;
import org.apache.etch.bindings.java.support.DefaultValueFactory;


/**
 * ValueFactory for WebLink.
 */
@SuppressWarnings("unused")
public final class ValueFactoryWebLink extends DefaultValueFactory
{
	/**
	 * Constructs ValueFactoryWebLink.
	 * @param uri the uri used to configure the session.
	 */
	public ValueFactoryWebLink( String uri )
	{
		super( uri, types, class2type );
	}
	
	private final static TypeMap types = new TypeMap();
	
	private final static Class2TypeMap class2type = new Class2TypeMap();

	static
	{
		DefaultValueFactory.init( types, class2type );
		initTypes();
		initResults();
		initFields();
		initParams();
	}

	/** Type for com.obigo.weblink.WebLink.RemoteControl */
	public static Type _mt_com_obigo_weblink_WebLink_RemoteControl;

	/** Type for com.obigo.weblink.WebLink.remote_control */
	public static Type _mt_com_obigo_weblink_WebLink_remote_control;

	/** Type for com.obigo.weblink.WebLink._result_remote_control */
	public static Type _mt_com_obigo_weblink_WebLink__result_remote_control;

	/** Type for com.obigo.weblink.WebLink.RadioStation */
	public static Type _mt_com_obigo_weblink_WebLink_RadioStation;

	/** Type for com.obigo.weblink.WebLink.radio_station_list */
	public static Type _mt_com_obigo_weblink_WebLink_radio_station_list;

	/** Type for com.obigo.weblink.WebLink._result_radio_station_list */
	public static Type _mt_com_obigo_weblink_WebLink__result_radio_station_list;

	/** Type for com.obigo.weblink.WebLink.radio_station_count */
	public static Type _mt_com_obigo_weblink_WebLink_radio_station_count;

	/** Type for com.obigo.weblink.WebLink._result_radio_station_count */
	public static Type _mt_com_obigo_weblink_WebLink__result_radio_station_count;

	/** Type for com.obigo.weblink.WebLink.radio_station_get_at */
	public static Type _mt_com_obigo_weblink_WebLink_radio_station_get_at;

	/** Type for com.obigo.weblink.WebLink._result_radio_station_get_at */
	public static Type _mt_com_obigo_weblink_WebLink__result_radio_station_get_at;

	/** Type for com.obigo.weblink.WebLink.radio_station_select */
	public static Type _mt_com_obigo_weblink_WebLink_radio_station_select;

	/** Type for com.obigo.weblink.WebLink._result_radio_station_select */
	public static Type _mt_com_obigo_weblink_WebLink__result_radio_station_select;

	private static void initTypes()
	{
		_mt_com_obigo_weblink_WebLink_RemoteControl = types.get( "com.obigo.weblink.WebLink.RemoteControl" );
		_mt_com_obigo_weblink_WebLink_remote_control = types.get( "com.obigo.weblink.WebLink.remote_control" );
		_mt_com_obigo_weblink_WebLink__result_remote_control = types.get( "com.obigo.weblink.WebLink._result_remote_control" );
		_mt_com_obigo_weblink_WebLink_RadioStation = types.get( "com.obigo.weblink.WebLink.RadioStation" );
		_mt_com_obigo_weblink_WebLink_radio_station_list = types.get( "com.obigo.weblink.WebLink.radio_station_list" );
		_mt_com_obigo_weblink_WebLink__result_radio_station_list = types.get( "com.obigo.weblink.WebLink._result_radio_station_list" );
		_mt_com_obigo_weblink_WebLink_radio_station_count = types.get( "com.obigo.weblink.WebLink.radio_station_count" );
		_mt_com_obigo_weblink_WebLink__result_radio_station_count = types.get( "com.obigo.weblink.WebLink._result_radio_station_count" );
		_mt_com_obigo_weblink_WebLink_radio_station_get_at = types.get( "com.obigo.weblink.WebLink.radio_station_get_at" );
		_mt_com_obigo_weblink_WebLink__result_radio_station_get_at = types.get( "com.obigo.weblink.WebLink._result_radio_station_get_at" );
		_mt_com_obigo_weblink_WebLink_radio_station_select = types.get( "com.obigo.weblink.WebLink.radio_station_select" );
		_mt_com_obigo_weblink_WebLink__result_radio_station_select = types.get( "com.obigo.weblink.WebLink._result_radio_station_select" );
	}

	private static void initResults()
	{
		_mt_com_obigo_weblink_WebLink_remote_control.setDirection( Direction.SERVER );
		_mt_com_obigo_weblink_WebLink_remote_control.setAsyncMode( AsyncMode.NONE );
		_mt_com_obigo_weblink_WebLink_remote_control.setResult( _mt_com_obigo_weblink_WebLink__result_remote_control );
		_mt_com_obigo_weblink_WebLink__result_remote_control.setTimeout( 0 );
		_mt_com_obigo_weblink_WebLink__result_remote_control.setDirection( Direction.CLIENT );
		_mt_com_obigo_weblink_WebLink_radio_station_list.setDirection( Direction.SERVER );
		_mt_com_obigo_weblink_WebLink_radio_station_list.setAsyncMode( AsyncMode.NONE );
		_mt_com_obigo_weblink_WebLink_radio_station_list.setResult( _mt_com_obigo_weblink_WebLink__result_radio_station_list );
		_mt_com_obigo_weblink_WebLink__result_radio_station_list.setTimeout( 0 );
		_mt_com_obigo_weblink_WebLink__result_radio_station_list.setDirection( Direction.CLIENT );
		_mt_com_obigo_weblink_WebLink_radio_station_count.setDirection( Direction.SERVER );
		_mt_com_obigo_weblink_WebLink_radio_station_count.setAsyncMode( AsyncMode.NONE );
		_mt_com_obigo_weblink_WebLink_radio_station_count.setResult( _mt_com_obigo_weblink_WebLink__result_radio_station_count );
		_mt_com_obigo_weblink_WebLink__result_radio_station_count.setTimeout( 0 );
		_mt_com_obigo_weblink_WebLink__result_radio_station_count.setDirection( Direction.CLIENT );
		_mt_com_obigo_weblink_WebLink_radio_station_get_at.setDirection( Direction.SERVER );
		_mt_com_obigo_weblink_WebLink_radio_station_get_at.setAsyncMode( AsyncMode.NONE );
		_mt_com_obigo_weblink_WebLink_radio_station_get_at.setResult( _mt_com_obigo_weblink_WebLink__result_radio_station_get_at );
		_mt_com_obigo_weblink_WebLink__result_radio_station_get_at.setTimeout( 0 );
		_mt_com_obigo_weblink_WebLink__result_radio_station_get_at.setDirection( Direction.CLIENT );
		_mt_com_obigo_weblink_WebLink_radio_station_select.setDirection( Direction.SERVER );
		_mt_com_obigo_weblink_WebLink_radio_station_select.setAsyncMode( AsyncMode.NONE );
		_mt_com_obigo_weblink_WebLink_radio_station_select.setResult( _mt_com_obigo_weblink_WebLink__result_radio_station_select );
		_mt_com_obigo_weblink_WebLink__result_radio_station_select.setTimeout( 0 );
		_mt_com_obigo_weblink_WebLink__result_radio_station_select.setDirection( Direction.CLIENT );
	}

	static
	{
		class2type.put( com.obigo.weblink.WebLink.RemoteControl.class, _mt_com_obigo_weblink_WebLink_RemoteControl );
		_mt_com_obigo_weblink_WebLink_RemoteControl.setComponentType( com.obigo.weblink.WebLink.RemoteControl.class );
		_mt_com_obigo_weblink_WebLink_RemoteControl.setImportExportHelper( new ImportExportHelper()
		{
			public final StructValue exportValue( ValueFactory vf, Object value )
			{
				StructValue struct = new StructValue( _mt_com_obigo_weblink_WebLink_RemoteControl, vf );
				com.obigo.weblink.WebLink.RemoteControl v = (com.obigo.weblink.WebLink.RemoteControl) value;
				switch (v)
				{
					case VOLUME_UP: struct.put( _mf_VOLUME_UP, true ); break;
					case VOLUME_DOWN: struct.put( _mf_VOLUME_DOWN, true ); break;
					case PLAY: struct.put( _mf_PLAY, true ); break;
					case PAUSE: struct.put( _mf_PAUSE, true ); break;
					case NEXT: struct.put( _mf_NEXT, true ); break;
					case PREV: struct.put( _mf_PREV, true ); break;
				}
				return struct;
			}

			public final Object importValue( StructValue struct )
			{
				// if empty, it likely means that a null value was sent
				// or an unknown key (from a different rev of the service).
				if (struct.isEmpty())
					return null;
				
				// there should only be a single key, so take the first one
				Field key = struct.keySet().iterator().next();
				if (key == _mf_VOLUME_UP) return com.obigo.weblink.WebLink.RemoteControl.VOLUME_UP;
				if (key == _mf_VOLUME_DOWN) return com.obigo.weblink.WebLink.RemoteControl.VOLUME_DOWN;
				if (key == _mf_PLAY) return com.obigo.weblink.WebLink.RemoteControl.PLAY;
				if (key == _mf_PAUSE) return com.obigo.weblink.WebLink.RemoteControl.PAUSE;
				if (key == _mf_NEXT) return com.obigo.weblink.WebLink.RemoteControl.NEXT;
				if (key == _mf_PREV) return com.obigo.weblink.WebLink.RemoteControl.PREV;

				// a known key was sent, but it did not match any defined
				// key for this type.
				return null;
			}
		} );
	}

	static
	{
		class2type.put( com.obigo.weblink.WebLink.RadioStation.class, _mt_com_obigo_weblink_WebLink_RadioStation );
		_mt_com_obigo_weblink_WebLink_RadioStation.setComponentType( com.obigo.weblink.WebLink.RadioStation.class );
		_mt_com_obigo_weblink_WebLink_RadioStation.setImportExportHelper( new ImportExportHelper()
		{
			public final StructValue exportValue( ValueFactory vf, Object value )
			{
				StructValue struct = new StructValue( _mt_com_obigo_weblink_WebLink_RadioStation, vf );
				com.obigo.weblink.WebLink.RadioStation v = (com.obigo.weblink.WebLink.RadioStation) value;
				struct.put( _mf_id, v.id );
				struct.put( _mf_title, v.title );
				struct.put( _mf_genre, v.genre );
				struct.put( _mf_url, v.url );
				struct.put( _mf_thumb, v.thumb );
				return struct;
			}

			public final Object importValue( StructValue struct )
			{
				com.obigo.weblink.WebLink.RadioStation v = new com.obigo.weblink.WebLink.RadioStation();
				v.id = (Integer) struct.get( _mf_id );
				v.title = (String) struct.get( _mf_title );
				v.genre = (String) struct.get( _mf_genre );
				v.url = (String) struct.get( _mf_url );
				v.thumb = (String) struct.get( _mf_thumb );
				return v;
			}
		} );
	}

	/** Field for VOLUME_UP */
	public static Field _mf_VOLUME_UP;

	/** Field for VOLUME_DOWN */
	public static Field _mf_VOLUME_DOWN;

	/** Field for PLAY */
	public static Field _mf_PLAY;

	/** Field for PAUSE */
	public static Field _mf_PAUSE;

	/** Field for NEXT */
	public static Field _mf_NEXT;

	/** Field for PREV */
	public static Field _mf_PREV;

	/** Field for control */
	public static Field _mf_control;

	/** Field for id */
	public static Field _mf_id;

	/** Field for title */
	public static Field _mf_title;

	/** Field for genre */
	public static Field _mf_genre;

	/** Field for url */
	public static Field _mf_url;

	/** Field for thumb */
	public static Field _mf_thumb;

	/** Field for index */
	public static Field _mf_index;

	/** Field for radio_station_id */
	public static Field _mf_radio_station_id;

	private static void initFields()
	{
		_mf_VOLUME_UP = new Field( "VOLUME_UP" );
		_mf_VOLUME_DOWN = new Field( "VOLUME_DOWN" );
		_mf_PLAY = new Field( "PLAY" );
		_mf_PAUSE = new Field( "PAUSE" );
		_mf_NEXT = new Field( "NEXT" );
		_mf_PREV = new Field( "PREV" );
		_mf_control = new Field( "control" );
		_mf_id = new Field( "id" );
		_mf_title = new Field( "title" );
		_mf_genre = new Field( "genre" );
		_mf_url = new Field( "url" );
		_mf_thumb = new Field( "thumb" );
		_mf_index = new Field( "index" );
		_mf_radio_station_id = new Field( "radio_station_id" );

		_mt_com_obigo_weblink_WebLink__result_remote_control.setResponseField( _mf_result );
		_mt_com_obigo_weblink_WebLink__result_radio_station_list.setResponseField( _mf_result );
		_mt_com_obigo_weblink_WebLink__result_radio_station_count.setResponseField( _mf_result );
		_mt_com_obigo_weblink_WebLink__result_radio_station_get_at.setResponseField( _mf_result );
		_mt_com_obigo_weblink_WebLink__result_radio_station_select.setResponseField( _mf_result );
	}
	
	static
	{
		// initialize the extern serializers:
	}

	private static void initParams()
	{

		// params for RemoteControl
		_mt_com_obigo_weblink_WebLink_RemoteControl.putValidator( _mf_VOLUME_UP, org.apache.etch.bindings.java.support.Validator_boolean.get( 0 ) );
		_mt_com_obigo_weblink_WebLink_RemoteControl.putValidator( _mf_VOLUME_DOWN, org.apache.etch.bindings.java.support.Validator_boolean.get( 0 ) );
		_mt_com_obigo_weblink_WebLink_RemoteControl.putValidator( _mf_PLAY, org.apache.etch.bindings.java.support.Validator_boolean.get( 0 ) );
		_mt_com_obigo_weblink_WebLink_RemoteControl.putValidator( _mf_PAUSE, org.apache.etch.bindings.java.support.Validator_boolean.get( 0 ) );
		_mt_com_obigo_weblink_WebLink_RemoteControl.putValidator( _mf_NEXT, org.apache.etch.bindings.java.support.Validator_boolean.get( 0 ) );
		_mt_com_obigo_weblink_WebLink_RemoteControl.putValidator( _mf_PREV, org.apache.etch.bindings.java.support.Validator_boolean.get( 0 ) );

		// params for remote_control
		_mt_com_obigo_weblink_WebLink_remote_control.putValidator( _mf_control, org.apache.etch.bindings.java.support.Validator_custom.get( com.obigo.weblink.WebLink.RemoteControl.class, 0, false ) );
		_mt_com_obigo_weblink_WebLink_remote_control.putValidator( _mf__messageId, org.apache.etch.bindings.java.support.Validator_long.get( 0 ) );

		// params for _result_remote_control
		_mt_com_obigo_weblink_WebLink__result_remote_control.putValidator( _mf_result, org.apache.etch.bindings.java.support.Validator_void.get( 0 ) );
		_mt_com_obigo_weblink_WebLink__result_remote_control.putValidator( _mf__messageId, org.apache.etch.bindings.java.support.Validator_long.get( 0 ) );
		_mt_com_obigo_weblink_WebLink__result_remote_control.putValidator( _mf_result, org.apache.etch.bindings.java.support.Validator_RuntimeException.get() ); // thrown RuntimeException
		_mt_com_obigo_weblink_WebLink__result_remote_control.putValidator( _mf__inReplyTo, org.apache.etch.bindings.java.support.Validator_long.get( 0 ) );

		// params for RadioStation
		_mt_com_obigo_weblink_WebLink_RadioStation.putValidator( _mf_id, org.apache.etch.bindings.java.support.Validator_int.get( 0 ) );
		_mt_com_obigo_weblink_WebLink_RadioStation.putValidator( _mf_title, org.apache.etch.bindings.java.support.Validator_string.get( 0 ) );
		_mt_com_obigo_weblink_WebLink_RadioStation.putValidator( _mf_genre, org.apache.etch.bindings.java.support.Validator_string.get( 0 ) );
		_mt_com_obigo_weblink_WebLink_RadioStation.putValidator( _mf_url, org.apache.etch.bindings.java.support.Validator_string.get( 0 ) );
		_mt_com_obigo_weblink_WebLink_RadioStation.putValidator( _mf_thumb, org.apache.etch.bindings.java.support.Validator_string.get( 0 ) );

		// params for radio_station_list
		_mt_com_obigo_weblink_WebLink_radio_station_list.putValidator( _mf__messageId, org.apache.etch.bindings.java.support.Validator_long.get( 0 ) );

		// params for _result_radio_station_list
		_mt_com_obigo_weblink_WebLink__result_radio_station_list.putValidator( _mf_result, org.apache.etch.bindings.java.support.Validator_custom.get( com.obigo.weblink.WebLink.RadioStation.class, 1, true ) );
		_mt_com_obigo_weblink_WebLink__result_radio_station_list.putValidator( _mf__messageId, org.apache.etch.bindings.java.support.Validator_long.get( 0 ) );
		_mt_com_obigo_weblink_WebLink__result_radio_station_list.putValidator( _mf_result, org.apache.etch.bindings.java.support.Validator_RuntimeException.get() ); // thrown RuntimeException
		_mt_com_obigo_weblink_WebLink__result_radio_station_list.putValidator( _mf__inReplyTo, org.apache.etch.bindings.java.support.Validator_long.get( 0 ) );

		// params for radio_station_count
		_mt_com_obigo_weblink_WebLink_radio_station_count.putValidator( _mf__messageId, org.apache.etch.bindings.java.support.Validator_long.get( 0 ) );

		// params for _result_radio_station_count
		_mt_com_obigo_weblink_WebLink__result_radio_station_count.putValidator( _mf_result, org.apache.etch.bindings.java.support.Validator_int.get( 0 ) );
		_mt_com_obigo_weblink_WebLink__result_radio_station_count.putValidator( _mf__messageId, org.apache.etch.bindings.java.support.Validator_long.get( 0 ) );
		_mt_com_obigo_weblink_WebLink__result_radio_station_count.putValidator( _mf_result, org.apache.etch.bindings.java.support.Validator_RuntimeException.get() ); // thrown RuntimeException
		_mt_com_obigo_weblink_WebLink__result_radio_station_count.putValidator( _mf__inReplyTo, org.apache.etch.bindings.java.support.Validator_long.get( 0 ) );

		// params for radio_station_get_at
		_mt_com_obigo_weblink_WebLink_radio_station_get_at.putValidator( _mf_index, org.apache.etch.bindings.java.support.Validator_int.get( 0 ) );
		_mt_com_obigo_weblink_WebLink_radio_station_get_at.putValidator( _mf__messageId, org.apache.etch.bindings.java.support.Validator_long.get( 0 ) );

		// params for _result_radio_station_get_at
		_mt_com_obigo_weblink_WebLink__result_radio_station_get_at.putValidator( _mf_result, org.apache.etch.bindings.java.support.Validator_custom.get( com.obigo.weblink.WebLink.RadioStation.class, 0, true ) );
		_mt_com_obigo_weblink_WebLink__result_radio_station_get_at.putValidator( _mf__messageId, org.apache.etch.bindings.java.support.Validator_long.get( 0 ) );
		_mt_com_obigo_weblink_WebLink__result_radio_station_get_at.putValidator( _mf_result, org.apache.etch.bindings.java.support.Validator_RuntimeException.get() ); // thrown RuntimeException
		_mt_com_obigo_weblink_WebLink__result_radio_station_get_at.putValidator( _mf__inReplyTo, org.apache.etch.bindings.java.support.Validator_long.get( 0 ) );

		// params for radio_station_select
		_mt_com_obigo_weblink_WebLink_radio_station_select.putValidator( _mf_radio_station_id, org.apache.etch.bindings.java.support.Validator_int.get( 0 ) );
		_mt_com_obigo_weblink_WebLink_radio_station_select.putValidator( _mf__messageId, org.apache.etch.bindings.java.support.Validator_long.get( 0 ) );

		// params for _result_radio_station_select
		_mt_com_obigo_weblink_WebLink__result_radio_station_select.putValidator( _mf_result, org.apache.etch.bindings.java.support.Validator_void.get( 0 ) );
		_mt_com_obigo_weblink_WebLink__result_radio_station_select.putValidator( _mf__messageId, org.apache.etch.bindings.java.support.Validator_long.get( 0 ) );
		_mt_com_obigo_weblink_WebLink__result_radio_station_select.putValidator( _mf_result, org.apache.etch.bindings.java.support.Validator_RuntimeException.get() ); // thrown RuntimeException
		_mt_com_obigo_weblink_WebLink__result_radio_station_select.putValidator( _mf__inReplyTo, org.apache.etch.bindings.java.support.Validator_long.get( 0 ) );
	}
	
	static
	{
		// done updating types, and class2type: lock them.
		types.lock();
		for (Type t: types.values())
			t.lock();
		class2type.lock();
	}
}
