// This file automatically generated by:
//   Apache Etch 1.3.0-incubating (LOCAL-0) / java 1.3.0-incubating (LOCAL-0)
//   Thu Sep 26 14:54:45 KST 2013
// This file is automatically created and should not be edited!
// Re-implement these methods by overriding them in ImplWebLinkClient.

package com.obigo.weblink;

import org.apache.etch.bindings.java.support.ObjSession;


/**
 * Base implementation of WebLinkClient, with default method implementations
 * which throw UnsupportedOperationException. Extend this class to provide
 * implementations of messages from the server.
 *
 * @see ImplWebLinkClient
 */
public class BaseWebLinkClient implements WebLinkClient, ObjSession
{
	public Object _sessionQuery( Object query ) throws Exception
	{
		throw new UnsupportedOperationException( "unknown query: "+query );
	}

	public void _sessionControl( Object control, Object value ) throws Exception
	{
		throw new UnsupportedOperationException( "unknown control: "+control );
	}

	public void _sessionNotify( Object event ) throws Exception
	{
		if (event instanceof Throwable)
			((Throwable) event).printStackTrace();
	}
}
