// This file automatically generated by:
//   Apache Etch 1.3.0-incubating (LOCAL-0) / java 1.3.0-incubating (LOCAL-0)
//   Thu Sep 26 14:54:45 KST 2013
// This file is automatically created for your convenience and will not be
// overwritten once it exists! Please edit this file as necessary to implement
// your service logic.

package com.obigo.weblink;

import org.apache.etch.bindings.java.support.ServerFactory;
import org.apache.etch.util.core.io.Transport;

/**
 * Main program for WebLinkServer. This program makes a listener to accept
 * connections from MainWebLinkClient.
 */
public class MainWebLinkListener implements WebLinkHelper.WebLinkServerFactory
{
	/**
	 * Main program for WebLinkServer.
	 * 
	 * @param args command line arguments.
	 * @throws Exception
	 */
	public static void main( String[] args ) throws Exception
	{
		// TODO Change to correct URI
		String uri = "tcp://0.0.0.0:4001";
		
		ServerFactory listener = WebLinkHelper.newListener( uri, null,
			new MainWebLinkListener() );

		// Start the Listener
		listener.transportControl( Transport.START_AND_WAIT_UP, 4000 );
	}

	public WebLinkServer newWebLinkServer( RemoteWebLinkClient client )
	{
		return new ImplWebLinkServer( client );
	}
}
